### ISSUE TITLE
Queue Status in Solid queue jobs misleading

### ISSUE THREAD

**Issue by juliancheal** [avo-hq/solid_queue-app-blueprint#1]
Hey @adrianthedev, firstly I got Avo and Avo's Soild Queue setup in minutes, bravo! 🎉

One thing though as I was also using Solid Queue for the first time, I was making sure it was actually running my jobs, as I'm migrating from using Sidekiq. And for longer than I care to mention I thought Solid Queue wasn't finishing running my jobs. 

As you can see there is a nice big badge that says `running`.
![Screenshot 2024-01-08 at 23 09 16](https://github.com/avo-hq/solid_queue-app-template/assets/63991/51667ef5-3d9f-4053-83a0-5aed3ae68b13)

I realised afterwards, that it was related to the queue and not the job, and noticing the `finished at` time (how I didn't notice that 🙈) I realised they had indeed run.

So I was wondering what you thought to changing this column to be the `job status` and not the `queue_status`?

I was just playing around to see if using `SolidQueue::ClaimedExecution` would work, it kind of does, but we'd then want to check the other `execution` tables too, and now this got a lot more complicated.

I'm interested to hear your thoughts.

**Comment by adrianthedev** [comment]
I don't know too much about how SQ takes and executes jobs.
One thought that I have is that most jobs are executed in milliseconds and they don't need that badge.
But for those jobs that take longer, that would be useful.

As you "hit this issue" more than I did, I'm open to suggestions from you 😛.

> I was just playing around to see if using SolidQueue::ClaimedExecution would work, it kind of does, but we'd then want to check the other execution tables too, and now this got a lot more complicated.

If that's a `has_one` association, it will be easy to display the status here using a computed field.

**Comment by adrianthedev** [comment]
I don't know too much about how SQ takes and executes jobs.
One thought that I have is that most jobs are executed in milliseconds and they don't need that badge.
But for those jobs that take longer, that would be useful.

As you "hit this issue" more than I did, I'm open to suggestions from you 😛.

> I was just playing around to see if using SolidQueue::ClaimedExecution would work, it kind of does, but we'd then want to check the other execution tables too, and now this got a lot more complicated.

If that's a `has_one` association, it will be easy to display the status here using a computed field.

**Comment by juliancheal** [comment]
Coolio, I'll take a look and see what I can do.
